# Generated by Django 4.0.4 on 2022-04-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('topic', models.TextField(max_length=200)),
            ],
        ),
    ]
